### PR TITLE
feat: integrate sds protocol.

### PR DESCRIPTION
**Pull request by kaichaosun**
SDS is a protocol to improve reliability of community messages. [SDS spec](https://github.com/vacp2p/rfc-index/blob/main/vac/raw/sds.md)

A description to understand introduced changes without reading the code.

Important changes:
- [x] Add channel id in `ApplicationMetadataMessage` for SDS
- [x] Wrap message with SDS manager.
- [x] Unwrap message with SDS manager.
- [ ]  Add unit tests

Relates #https://github.com/waku-org/pm/issues/194

### CODE REVIEW

**Review by jm-clius — COMMENTED** [review]
Thanks! Looked through this and it seems reasonable to me - at least the functionality of wrapping and unwrapping a message. Would be great to see more of the callbacks stubbed (perhaps in a next PR?). The idea of the basic integration is simply to add logs that demonstrate what kind of reliability information we get from SDS, as you are indeed doing. Are there any other mechanisms (e.g. metrics) available to make monitoring even easier?

**Comment by kaichaosun** [comment]
> Are there any other mechanisms (e.g. metrics) available to make monitoring even easier?

The grafana & promethues can probably help, but looks not straight forward since we likely want to track the graph somehow.

@jm-clius

**Comment by siddarthkay** [comment]
builds from this PR will stay in build queue in CI unless rebased, please do so.
Thank you!

**Comment by kaichaosun** [comment]
@siddarthkay I have merged the latest develop branch, is it ok or I have to do the rebase?

File: vendor/modules.txt [hunk 1]
```diff
@@ -1115,6 +1115,9 @@ github.com/waku-org/go-zerokit-rln-x86_64/libs/x86_64-pc-windows-gnu
 github.com/waku-org/go-zerokit-rln-x86_64/libs/x86_64-unknown-linux-gnu
 github.com/waku-org/go-zerokit-rln-x86_64/libs/x86_64-unknown-linux-musl
 github.com/waku-org/go-zerokit-rln-x86_64/rln
+# github.com/waku-org/sds-go-bindings v0.0.0-20250724095249-05e797c76b8c
+## explicit; go 1.22.10
```
Comment (siddarthkay) [inline vendor/modules.txt]: I guess this part also would need adjustment since we no longer build with go 1.22 on CI.
We upgraded go to 1.23 a while ago.

Comment (kaichaosun) [reply vendor/modules.txt]: @Ivansete-status is it safe to upgrade the go version for this bindings? I have tried upgrade the golang version, but tests failed with error,
```
sds/sds.go:61:15: error: call to undeclared function 'SdsNewReliabilityManager'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-decla
ration]
                void* ret = SdsNewReliabilityManager((SdsCallBack) SdsGoCallback, resp);
                            ^
sds/sds.go:61:9: error: incompatible integer to pointer conversion initializing 'void *' with an expression of type 'int' [-Wint-conversion]
                void* ret = SdsNewReliabilityManager((SdsCallBack) SdsGoCallback, resp);
                      ^     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
sds/sds.go:78:3: error: call to undeclared function 'SdsSetEventCallback'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration
]
                SdsSetEventCallback(rmCtx, (SdsCallBack) sdsGlobalEventCallback, rmCtx);
                ^
sds/sds.go:82:3: error: call to undeclared function 'SdsCleanupReliabilityManager'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-de
claration]
```

Comment (siddarthkay) [reply vendor/modules.txt]: we can probably fix those errors by setting `CFLAGS="-Wno-error=implicit-function-declaration"`

File: messaging/common/message_sender.go [hunk 2]
```diff
@@ -74,16 +78,40 @@ func NewMessageSender(
...
+	reliabilityManager, err := sds.NewReliabilityManager()
+	if err != nil {
+		return nil, errors.Wrap(err, "SDS: failed to create reliability manager")
+	}
+	callbacks := sds.EventCallbacks{
+		OnMessageSent: func(messageId sds.MessageID, channelId string) {
+			logger.Debug("SDS: message sent", zap.String("messageId", string(messageId)), zap.String("channelId", channelId))
+		},
+		OnMissingDependencies: func(messageId sds.MessageID, missingDeps []sds.MessageID, channelId string) {
+			logger.Debug("SDS: missing dependencies",
```
Comment (plopezlpz) [inline messaging/common/message_sender.go:92]: I don't know how the sds lib works but if there are missing deps shouldn't we "request" them somehow or does the library does it automatically?

Comment (kaichaosun) [reply messaging/common/message_sender.go:92]: @jm-clius mentioned that in the first delivery, only logging is ok.  There are [some discussions on discord](https://discord.com/channels/1110799176264056863/1401730910189125706/1402814422640103474) on how to use SDS, specifically about the missing dependencies, it seems not polished yet.  cc @shash256

Comment (jm-clius) [reply messaging/common/message_sender.go:92]: Indeed, to make this a little bit more digestible, we have split the deliverable into two:
1. basic integration - where we simply "log" reliability information from SDS to show that it can work within Status: https://github.com/waku-org/pm/issues/194
2. basic recovery - where we use the information we log to try some basic recovery techniques: https://github.com/waku-org/pm/issues/304

Next step after integration would be to proceed with this recovery. @shash256 can be involved to brainstorm what strategies we can use.

**Review by xjc90s — APPROVED** [review]

File: Makefile [hunk 3]
```diff
@@ -182,7 +193,7 @@ status-go-deps:
 	go install github.com/kevinburke/go-bindata/v4/...@v4.0.2
 	go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.34.1
 
-statusgo-android: generate
+statusgo-android: generate-sds-android generate
```
Comment (siddarthkay) [inline Makefile:196]: you can avoid making changes to android target now, we will deprecate this way of linking soon.
I've made the jobs in CI optional.
The new mobile app will rely on `statusgo-shared-library` target.

**Comment by kaichaosun** [comment]
Replaced by this PR: https://github.com/status-im/status-go/pull/6884 @Ivansete-status
