### PR TITLE
chore: use go 1.20 and latest go-waku

### PR DESCRIPTION
**Pull request by richard-ramos**
*See title*

### CODE REVIEW

**Comment by richard-ramos** [comment]
@jakubgs , while i was attempting to upgrade to go1.21, i ended up with this error in nix:
```
[2024-01-03T22:21:05.635Z]        error: undefined variable 'go_1_21'
```
According to https://discourse.nixos.org/t/how-to-get-go-1-21-in-nix-shell/33433/3 it seems that the default go version is now 1.21 and there is no go_1_21 package, but seems weird to not specify the go version. Your advice is appreciated!

**Comment by jakubgs** [comment]
@richard-ramos remember that the packages available form Nix are controlled by the version of `nixpkgs` repo used, which in our case is controlled in the `shell.nix` by specifying a `nixpkgs` commit:
https://github.com/status-im/status-go/blob/846a4e2363723bf8c32e94c4674a2c44ae48e62a/shell.nix#L2-L7
If you look at the `e7603eba51f2c7820c0a182c6bbb351181caa8e7` commit you'll see it doesn't contain Go `1.21`:
https://github.com/NixOS/nixpkgs/tree/e7603eba51f2c7820c0a182c6bbb351181caa8e7/pkgs/development/compilers/go

Now as the comment states, this should be the same version as used in `status-mobile` to avoid diverging behaviors due to different tooling and libraries, but a temporary divergence probably wouldn't be a big issue.

As for what to upgrade to, I would argue that using `master` might not be the best option, and I'd switch it to `nixos-23.11` to use a stable branch. Though I would prefer to start the upgrade with `status-mobile` as that will have more issues most probably.

**Comment by jakubgs** [comment]
And actually, @siddarthkay is attempting a Nixpkgs upgrade in here:

* https://github.com/status-im/status-mobile/pull/18321

So you might want to sync with him as to what version to use.

**Comment by richard-ramos** [comment]
> @jakubgs: remember that the packages available form Nix are controlled by the version of nixpkgs repo used, which in our case is controlled in the shell.nix by specifying a nixpkgs commit .... So you might want to sync with @siddarthkay as to what version to use.

Just checked 23.11, (the one used in mobile PR) and I see it contains the go version I need. I'll try changing it in this PR and see how it goes. 
image

Once https://github.com/status-im/status-mobile/pull/18321 is merged we can proceed to upgrade nix in status-go

**Comment by richard-ramos** [comment]
Looks like upgrading to go1.21 ends up causing issues in the torrent lib. (cc: @siddarthkay @chaitanyaprem), maybe there's a new version compatible with it.
```
[2024-01-10T15:21:41.590Z] vendor/github.com/anacrolix/go-libutp/callbacks.go:16:10: cannot define new methods on non-local type *C.utp_callback_arguments
[2024-01-10T15:21:41.590Z] vendor/github.com/anacrolix/go-libutp/callbacks.go:24:10: cannot define new methods on non-local type *C.utp_callback_arguments
[2024-01-10T15:21:41.590Z] vendor/github.com/anacrolix/go-libutp/callbacks.go:28:10: cannot define new methods on non-local type *C.utp_callback_arguments
[2024-01-10T15:21:41.590Z] vendor/github.com/anacrolix/go-libutp/callbacks.go:32:10: cannot define new methods on non-local type *C.utp_callback_arguments
[2024-01-10T15:21:41.590Z] vendor/github.com/anacrolix/go-libutp/callbacks.go:36:10: cannot define new methods on non-local type *C.utp_callback_arguments
[2024-01-10T15:21:41.590Z] vendor/github.com/anacrolix/go-libutp/utp.go:29:12: cannot define new methods on non-local type *C.utp_context
[2024-01-10T15:21:41.590Z] vendor/github.com/anacrolix/go-libutp/utp.go:40:12: cannot define new methods on non-local type *C.utp_context
```

**Comment by richard-ramos** [comment]
After changing the version of anacrolix/torrent, now gomobile has a different complain:
```
 unable to import bind/java: [-: # golang.org/x/mobile/bind/java
[2024-01-10T15:27:21.903Z] /nix/store/nb4a2r49nfnpfqhixfmzkxh38iighjk0-gomobile-unstable-2022-05-18/src/golang.org/x/mobile/bind/java/context_android.go:9:10: fatal error: jni.h: No such file or directory
[2024-01-10T15:27:21.903Z]     9 | //#include <jni.h>
[2024-01-10T15:27:21.903Z]       |          ^~~~~~~
[2024-01-10T15:27:21.903Z] compilation terminated.]
```
I did run into this before, so it seems we need to upgrade gomobile somehow?

**Comment by jakubgs** [comment]
To upgrade `gomobile` we need to override the `buildGoModule` attribute since the use of a builder makes this a nested derivation, so just using `overrideAttrs` on `gomobile` wouldn't be enough:
https://github.com/status-im/status-go/blob/df8b9554ecc0ea7e73c149c5357398add7db1dc7/shell.nix#L27-L39

For more details see:

* https://github.com/NixOS/nixpkgs/issues/86349
* https://discourse.nixos.org/t/how-to-cross-compile-using-buildgomodule/20775/23
* https://discourse.nixos.org/t/buildgomodule-with-specific-go-version-go-1-17/17442

**Comment by richard-ramos** [comment]
looks like there's a dependency that also includes sqlite and clashes with sqlcipher. I'm trying to figure out where this is happening

cc: @siddarthkay @chaitanyaprem 

```
[2024-01-10T19:51:53.371Z] ld: error: duplicate symbol: sqlite3_aggregate_context
[2024-01-10T19:51:53.371Z] >>> defined at sqlite3.c:89125
[2024-01-10T19:51:53.371Z] >>>            ../../go-link-3238948430/000084.o:(sqlite3_aggregate_context)
[2024-01-10T19:51:53.371Z] >>> defined at sqlite3.c:89261 (/home/jenkins/workspace/status-go_prs_android_PR-4522@tmp/go/src/github.com/status-im/status-go/vendor/github.com/go-llsqlite/crawshaw/./c/sqlite3.c:89261)
[2024-01-10T19:51:53.371Z] >>>            ../../go-link-3238948430/000111.o:(.text+0x103A0)
[2024-01-10T19:51:53.371Z] 
[2024-01-10T19:51:53.371Z] ld: error: duplicate symbol: sqlite3_auto_extension
[2024-01-10T19:51:53.371Z] >>> defined at sqlite3.c:138759
[2024-01-10T19:51:53.371Z] >>>            ../../go-link-3238948430/000084.o:(sqlite3_auto_extension)
[2024-01-10T19:51:53.371Z] >>> defined at sqlite3.c:134211 (/home/jenkins/workspace/status-go_prs_android_PR-4522@tmp/go/src/github.com/status-im/status-go/vendor/github.com/go-llsqlite/crawshaw/./c/sqlite3.c:134211)
[2024-01-10T19:51:53.371Z] >>>            ../../go-link-3238948430/000111.o:(.text+0x180E0)
...
```

**Comment by richard-ramos** [comment]
Oh. It's anacrolix/torrent

**Comment by richard-ramos** [comment]
@Samyoul @cammellos any idea what can be done here? we always have the option of forking anacrolix/torrent and removing any mention of sqlite there!

**Comment by richard-ramos** [comment]
In the meantime I'm downgrading to go1.20 (which still is better than 1.19), and am running into linting issues. Will attempt to fix these

**Comment by richard-ramos** [comment]
Seems to be working now, so in the meantime, let's use go 1.20, but work will be needed to get status-go to work with go1.21 due to dependencies included by `anacrolix/torrent`

cc: @cammellos @chaitanyaprem @iurimatias @jakubgs @Samyoul @siddarthkay

**Comment by ghost** [comment]
`vendor/github.com/pion/webrtc/v3/yarn.lock` changed. Pinging @corpetty

File: api/geth_backend.go [hunk 1]
```diff
@@ -269,11 +271,11 @@ func (b *GethStatusBackend) DeleteMultiaccount(keyUID string, keyStoreDir string
 		filepath.Join(b.rootDataDir, fmt.Sprintf("%s.db-shm", keyUID)),
 		filepath.Join(b.rootDataDir, fmt.Sprintf("%s.db-wal", keyUID)),
 		appDbPath,
-		appDbPath + "-shm",
-		appDbPath + "-wal",
+		appDbPath + shm,
+		appDbPath + "-wal", // nolint: goconst
```
Comment (igor-sirotin) [inline api/geth_backend.go:275]: I see where you got tired of fixing `goconst` 😄

**Review by igor-sirotin — APPROVED** [review]
💪

File: shell.nix [hunk 2]
```diff
@@ -1,17 +1,17 @@
 {
   /* This should match Nixpkgs commit in status-mobile. */
   source ? builtins.fetchTarball {
-    url = "https://github.com/NixOS/nixpkgs/archive/e7603eba51f2c7820c0a182c6bbb351181caa8e7.tar.gz";
-    sha256 = "sha256:0mwck8jyr74wh1b7g6nac1mxy6a0rkppz8n12andsffybsipz5jw";
+    url = "https://github.com/NixOS/nixpkgs/archive/ddf0003c57fb5cbb4a9754f2f6d5ebe9cdae5151.tar.gz";
```
Comment (jakubgs) [inline shell.nix]: Is this commit going to be used in `status-mobile` as well?

**Review by jakubgs — APPROVED** [review]

File: shell.nix (hunk 2 above)
Comment (richard-ramos) [reply shell.nix]: Should be! i copied it from https://github.com/status-im/status-mobile/pull/18321 so it probably makes sense to merge both this PR and that one once approved

Comment (siddarthkay) [reply shell.nix]: hmm 
we cant use this url -> https://github.com/NixOS/nixpkgs/archive/ddf0003c57fb5cbb4a9754f2f6d5ebe9cdae5151.tar.gz since its from nixpkgs master branch, what I had in the status-mobile PR back then was an experiment :D 

Here is what I'll do next week : 
- open PR with this status-go version in status-mobile to see what breaks and what doesn't.
- we'll verify if any `nixpkgs` stable version 23.11 got the fixes we want related to `GraalVM` or not ( else we just fork and move on )

and then what url we decide on at status-mobile we can use that here.

**Comment by siddarthkay** [comment]
> but work will be needed to get status-go to work with go1.21 due to dependencies included by `anacrolix/torrent`

Hey @richard-ramos : can you create an issue with the error you faced and I can take a look for what we can do to get the torrent package to work with go 1.21

File: shell.nix (hunk 2 above)
Comment (siddarthkay) [reply shell.nix]: actually for now you could just use : `e7603eba51f2c7820c0a182c6bbb351181caa8e7`
since we do have go 1.20 over here -> https://github.com/NixOS/nixpkgs/blob/e7603eba51f2c7820c0a182c6bbb351181caa8e7/pkgs/development/compilers/go/1.20.nix

Comment (richard-ramos) [reply shell.nix]: Alright! will do that

**Comment by ghost** [comment]
`vendor/github.com/pion/webrtc/v3/yarn.lock` changed. Pinging @corpetty

**Review by jakubgs — APPROVED** [review]
I'm approving the `shell.nix` changes.
